project_name: cidr-encoder

builds:
  -
    id: cidr-encoder
    main: ./cmd/cli/main.go
    binary: cidr-encoder
    flags:
      - -mod=readonly
    goos:
      - darwin
    goarch:
      - arm64

archives:
  -
    id: archive-cli
    builds:
      - cidr-encoder

    name_template: "tokenizer_cli_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

brews:
  -
    name: "cidr-encoder"

    repository:
      owner: jmoney
      name: homebrew-server-utils

      branch: main

      token: "{{ .Env.GITHUB_TOKEN }}"
    
    ids:
      - archive-cli

    # Git author used to commit to the repository.
    # Defaults are shown.
    commit_author:
      name: goreleaserbot
      email: noreply@gmail.com

    commit_msg_template: "Brew formula update for cidr-encoder version {{ .Tag }}"

    directory: Formula

    homepage: "https://jmoney.dev/cidr-encoder"

    description: "CLI for time efficiently encoding cidr blocks to find if an IP exists in a range"

    # SPDX identifier of your app's license.
    # Default is empty.
    license: "Apache 2.0"

    # Setting this will prevent goreleaser to actually try to commit the updated
    # formula - instead, the formula file will be stored on the dist folder only,
    # leaving the responsibility of publishing it to the user.
    # If set to auto, the release will not be uploaded to the homebrew tap
    # in case there is an indicator for prerelease in the tag e.g. v1.0.0-rc1
    # Default is false.
    #    skip_upload: true

    # So you can `brew test` your formula.
    # Default is empty.
    test: |
      system "#{bin}/cidr-encoder -h"

    # Custom install script for brew.
    # Default is 'bin.install "program"'.
    install: |
      bin.install "cidr-encoder"

  -
    name: "cidr-encoder@{{ .Tag }}"

    repository:
      owner: jmoney
      name: homebrew-server-utils

      branch: main

      token: "{{ .Env.GITHUB_TOKEN }}"
    
    ids:
      - archive-cli

    # Git author used to commit to the repository.
    # Defaults are shown.
    commit_author:
      name: goreleaserbot
      email: noreply@gmail.com

    commit_msg_template: "Brew formula update for cidr-encoder version {{ .Tag }}"

    directory: Formula

    homepage: "https://jmoney.dev/cidr-encoder"

    description: "CLI for time efficiently encoding cidr blocks to find if an IP exists in a range"

    # SPDX identifier of your app's license.
    # Default is empty.
    license: "Apache 2.0"

    # Setting this will prevent goreleaser to actually try to commit the updated
    # formula - instead, the formula file will be stored on the dist folder only,
    # leaving the responsibility of publishing it to the user.
    # If set to auto, the release will not be uploaded to the homebrew tap
    # in case there is an indicator for prerelease in the tag e.g. v1.0.0-rc1
    # Default is false.
    #    skip_upload: true

    # So you can `brew test` your formula.
    # Default is empty.
    test: |
      system "#{bin}/cidr-encoder -h"

    # Custom install script for brew.
    # Default is 'bin.install "program"'.
    install: |
      bin.install "cidr-encoder"