# Run golang tests on branch main

name: Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      -
        name: Set up Go
        uses: actions/setup-go@v4
        with:
            go-version: 1.22.3

      -
        name: Run Full Test Suite
        run: |
            go test -v -count=1 -timeout=60m ./internal/cidrencode
        timeout-minutes: 60